version: "3.8"

services:
  nginx:
    build: srcs/requirements/nginx/.
    container_name: inception_nginx
    ports:
      - "8080:80"
  wordpress:
    build: srcs/requirements/wordpress/.
    container_name: inception_wordpress

  mariadb:
    build: srcs/requirements/mariadb/.
    container_name: inception_mariadb