FROM debian:bookworm

RUN apt-get update && apt-get install -y mariadb-server && rm -rf /var/lib/apt/lists/*

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/mariadb.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/mariadb.sh \
    && install -d -o mysql -g mysql /var/lib/mysql /run/mysqld

ENTRYPOINT ["/usr/local/bin/mariadb.sh"]
